[package]
name = "lugha"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { version = "0.4", features = ["llvm14-0"] }
clap = { version = "4.5", features = ["derive"] }
nom = "7"
nom_locate = "4"
tempfile = "3"

[build-dependencies]
cc = "1.0"
